apiVersion: v1
kind: Namespace
metadata:
  name: meridian
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meridian-config
  namespace: meridian
data:
  # Global non-sensitive properties
  SPRING_PROFILES_ACTIVE: "prod"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  # DB Hosts
  POSTGRES_AUTH_HOST: "postgres-auth-service"
  POSTGRES_ORDER_HOST: "postgres-order-service"
  POSTGRES_NOTIFICATION_HOST: "postgres-notification-service"
  MONGO_HOST: "mongodb-service"
  REDIS_HOST: "redis-service"
  INFLUXDB_URL: "http://influxdb-service:8086"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-service:4318/v1/traces"
---
apiVersion: v1
kind: Secret
metadata:
  name: meridian-secrets
  namespace: meridian
type: Opaque
stringData:
  # Using stringData for auto base64 encoding by k8s
  JWT_SECRET: "MjAyNk1lcmlkaWFuQmFja2VuZE1hc3RlclNlY3JldEtleVN1cGVyU2FmZQ==" # Must be >= 256 bits for HS256
  POSTGRES_USER: "meridian"
  POSTGRES_PASSWORD: "changeme"
  MONGO_USERNAME: "meridian"
  MONGO_PASSWORD: "changeme"
  RABBITMQ_USERNAME: "meridian"
  RABBITMQ_PASSWORD: "changeme"
  INFLUXDB_TOKEN: "meridian-token"
  INFLUXDB_INIT_PASSWORD: "changeme123"
