apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace }}
data:
  # Global non-sensitive properties
  SPRING_PROFILES_ACTIVE: {{ .Values.global.springProfilesActive | quote }}
  RABBITMQ_HOST: "{{ .Release.Name }}-rabbitmq-service"
  RABBITMQ_PORT: "5672"
  # DB Hosts
  POSTGRES_AUTH_HOST: "{{ .Release.Name }}-postgres-auth-service"
  POSTGRES_ORDER_HOST: "{{ .Release.Name }}-postgres-order-service"
  POSTGRES_NOTIFICATION_HOST: "{{ .Release.Name }}-postgres-notification-service"
  MONGO_HOST: "{{ .Release.Name }}-mongodb-service"
  REDIS_HOST: "{{ .Release.Name }}-redis-service"
  INFLUXDB_URL: "http://{{ .Release.Name }}-influxdb-service:8086"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ .Release.Name }}-jaeger-service:4318/v1/traces"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  POSTGRES_USER: {{ .Values.global.credentials.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.credentials.postgresPassword | quote }}
  MONGO_USERNAME: {{ .Values.global.credentials.mongoUsername | quote }}
  MONGO_PASSWORD: {{ .Values.global.credentials.mongoPassword | quote }}
  RABBITMQ_USERNAME: {{ .Values.global.credentials.rabbitmqUsername | quote }}
  RABBITMQ_PASSWORD: {{ .Values.global.credentials.rabbitmqPassword | quote }}
  INFLUXDB_TOKEN: {{ .Values.global.credentials.influxdbToken | quote }}
  INFLUXDB_INIT_PASSWORD: {{ .Values.global.credentials.influxdbInitPassword | quote }}
