apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-influxdb
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: "{{ .Release.Name }}-influxdb-service"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-influxdb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-influxdb
    spec:
      containers:
        - name: influxdb
          image: {{ .Values.infrastructure.influxdb.image | quote }}
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "meridian"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: INFLUXDB_INIT_PASSWORD
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "meridian"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "analytics"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: INFLUXDB_TOKEN
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
  volumeClaimTemplates:
    - metadata:
        name: influxdb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.infrastructure.influxdb.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8086
  selector:
    app: {{ .Release.Name }}-influxdb
