apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-inventory-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.inventoryService.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-inventory-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-inventory-service
    spec:
      containers:
        - name: inventory-service
          image: "{{ .Values.services.inventoryService.image }}:{{ .Values.services.inventoryService.tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MONGO_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@{{ .Release.Name }}-mongodb-service:27017/inventory_db?authSource=admin"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: RABBITMQ_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: JWT_SECRET
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.services.inventoryService.javaOptions | quote }}
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: {{ .Release.Name }}-inventory-service
