apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jaeger
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-jaeger
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-jaeger
    spec:
      containers:
        - name: jaeger
          image: {{ .Values.infrastructure.jaeger.image | quote }}
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 16686
      name: ui
    - port: 4317
      name: otlp-grpc
    - port: 4318
      name: otlp-http
  selector:
    app: {{ .Release.Name }}-jaeger
