apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.orderService.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.services.orderService.image }}:{{ .Values.services.orderService.tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgres-order-service:5432/order_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: RABBITMQ_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: JWT_SECRET
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.services.orderService.javaOptions | quote }}
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ .Release.Name }}-order-service
